### ISSUE TITLE
WHERE ARE YOU?

### ISSUE THREAD

**Issue by NitkarshChourasia** [sach2212/javascripttut#16]
Hey, brother, where are you?

**Comment by NitkarshChourasia** [comment]
Add me as a collaborator, why removed me?
Also, push the code to testing branch, then Pull Request(PR) to main, and then assign me a  reviewer.
# Can you do it?!

**Comment by sach2212** [comment]
> Contributor

bhai tu kaha he roz i am adding js file
and asked too where are you

**Comment by NitkarshChourasia** [comment]
Ha, aise add karo.

**Comment by NitkarshChourasia** [comment]
Add me as a collaborator, why removed me?
Also, push the code to testing branch, then Pull Request(PR) to main, and then assign me a reviewer.

# Can you do it?!

**Comment by sach2212** [comment]
ha try kara hu

**Comment by NitkarshChourasia** [comment]
Nahi, try nahi...woh tumhara..na......review nahi kar pata hu.
Uske liye yeh karo, fir hi allow karrega github mujhe karne ko.
samjje?

**Comment by sach2212** [comment]
where do you reach in react

**Comment by sach2212** [comment]
> Nahi, try nahi...woh tumhara..na......review nahi kar pata hu. Uske liye yeh karo, fir hi allow karrega github mujhe karne ko. samjje?

haaaa

**Comment by NitkarshChourasia** [comment]
React toh nahi but frontend pe hu, filhal.
Bootstrap, HTML, CSS, Javascript.
Aur Backend start kar raha hu, dhire dhire.

**Comment by NitkarshChourasia** [comment]
mail me @ playnitkarsh@gmail.com
I want to send you a file. ASAP.

**Comment by NitkarshChourasia** [comment]
There

**Comment by sach2212** [comment]
backend ke chize please mujhse bhi share karte raho 🥲, vaise me bhi sab kari raha hu fir bhi basics samjhne ka try kara hu me nodes ke with implementation bas kuch pata chalta hoga to  batate raho

**Comment by sach2212** [comment]
> playnitkarsh@gmail.com

done

**Comment by NitkarshChourasia** [comment]
Did the steps?

**Comment by sach2212** [comment]
not showing as a reviewer

**Comment by NitkarshChourasia** [comment]
Wdym?

**Comment by sach2212** [comment]
while  doing PR it shows on the right side =" Reviewers " section
 but your name is not viisible

**Comment by NitkarshChourasia** [comment]
Make me a collaborator first, in the repo.

**Comment by NitkarshChourasia** [comment]
# FOLLOW THIS STEPS.
Add me as a collaborator, why removed me?
Also, push the code to testing branch, then Pull Request(PR) to main, and then assign me a reviewer.

Can you do it?!

**Comment by sach2212** [comment]
doing that only,
 wait trying

**Comment by sach2212** [comment]
> Make me a collaborator first, in the repo.

okhay

**Comment by NitkarshChourasia** [comment]
- Step 1: Make me repo collaborator. (then only reviewer assign will work for me, unless not)
- Step 2: Push the code to testing branch by `git checkout testing ; git add --all ; git commit -S -m"message." ; git push ; git pull`
- Step 3: Come and pull request to the main.
- Step 4: Assign me as a reviewer to the pull request you just did on the new commits.
- Step 5: Rest leave to me, your work has been done.

**Comment by NitkarshChourasia** [comment]
BUT DO THE MAIL THING.

**Comment by NitkarshChourasia** [comment]
Also.

**Comment by NitkarshChourasia** [comment]
Yes, you do your work.
Keep going.
As, I will get time, I will learn from them and would suggest edits.
Because, it is better to have quality then quantity.
Also, keep in mind, **SACHIN**, as soon as I suggest something improvements which will be worthy, do implement it **ASAP**, okay?

**Comment by NitkarshChourasia** [comment]
BECAUSE I WON'T LIKE IT YOU DON'T IMPLEMENT IT, AND I WILL NEED TO SUGGEST THE SAME MISTAKE IN EVERY PROGRAM AGAIN AND AGAIN, RIGHT?! OKAY. THEN ....THAT'S IT FOR TODAY, I GUESS.

**Comment by sach2212** [comment]
yeah  i will implement asap
but please

> backend ke chize please mujhse bhi share karte raho 🥲, vaise me bhi sab kari raha hu fir bhi basics samjhne ka try kara hu me nodes ke with implementation bas kuch pata chalta hoga to batate raho



---- let me know about this too
