### ISSUE TITLE
Hey, significant requirement.

### ISSUE THREAD

**Issue by NitkarshChourasia** [sach2212/javascripttut#24]
I wanted to review more programs, if you have any one in your circle of recognition, please refer them this way of code review if they are comfortable and want to improve. 
I wanted more code to review, it is quite fun....actually.

**Comment by sach2212** [comment]
except you no one is there😂

**Comment by NitkarshChourasia** [comment]
Yaar aisa toh apna college aur friends circle mai coding environment hai.
Ek hai purshottam but....he is too wise to keep colleagues.....he can't
work together but alone hahahaha 😅😜

**Comment by NitkarshChourasia** [comment]
Yaar!

**Comment by sach2212** [comment]
koi online community..?

**Comment by NitkarshChourasia** [comment]
Sab pro hai.... 😂 Online community mai.
