### ISSUE TITLE
Drills and Direct

### ISSUE THREAD

**Issue by PBJI** [sach2212/javascripttut#26]
Always try to keep balance between Drills and Direct practices.

Drills: Practicing same kind of small problems.
Direct: Practicing one big complex problem.

You are solving small javascript logic problem.
Now solve complex app level logic problems and use your gained js knowledge.

Take inspiration from somewhere. I made one project that taught me a great deal about javascript that these drills wouldn't teach you. (link: https://github.com/PBJI/ultimate-tictactoe-js/ ). Especially I learnt browser api's, where for some reason, I never understood the difference between browser api's and javascript until now, even though I did created an application without this distinction in mind.

My approach is simple, the problems I will face in an application are the only solution I will learn. This is procrastinator's way to get better at app development. DSA won't teach you to make an application, mind you. Keep both of them seperate, DSA helps in app development but quite at low level (optimization problems), not at the abstract levels we work with.

So start making project. Drop this drill thing or lower it's priority, believe me you would not regret. All the best. I will keep my attention open for further discussion and revert back.

**Comment by PBJI** [comment]
Perspectives to develop such application:

What are the logical feature that are separate from each other.
For example a game can be broken down into 3 basic process.

Take player input - Update game - Update the UI

Now I would think, how should I turn all of these logic into javascript.
1) Taking player input: I can use javascript event handlers on html elements. (O clicked x=5, y=4)
(I will then block the player inputs)
2) Update game: This logic can be broken into state and  further:
  a) Previous game state (X played on 5, 5)
  b) Update previous game state with new input (X played on x=5, y=5, O played on x=5, y=4)
3) Now update the UI: Using javascript, I will update the DOM or loosely saying the HTML. By adding or deleting DOM  elements. (like innerText = O)


This is just rough game logic breakdown. But I would further refine this logic more and more until and unless I am not satisfied with the gameplay myself (which is called as integrative testing in software development I guess).

**Comment by PBJI** [comment]
Skip third-party reviews, only take your own feedbacks, look at the console panel and debug using google. This will save your attention and time. This approach in terms of javascript you can call is nothing but synchronous approach where you block everybody until you create that fucking application by yourself.

Do this once, do this twice, then do only relevant drills (the small problems you faced during the development  or similar that were recurrent or frequent)

Like you faced a problem with regexp again and again a lot while developing the app, so after app development is finished now only do Regexp drills to perfect that part.

**Comment by sach2212** [comment]
sure!!

**Comment by NitkarshChourasia** [comment]
Don't tell show us, lead us, guide us, give us a project, with bugs and issues and optimizations to perform.
Talk is cheap, show us.

**Comment by NitkarshChourasia** [comment]
@PBJI I am capable of becoming the CEO of giant companies...
"Talk is cheap, show me the code." - Linus Torvalds

**Comment by PBJI** [comment]
Well I do have a project, I'll push it to remote and then let you guys know.

**Comment by NitkarshChourasia** [comment]
"Talk is cheap, show me the code." - Linus Torvalds

**Comment by NitkarshChourasia** [comment]
"Talk is cheap, show me the code." - Linus Torvalds

**Comment by NitkarshChourasia** [comment]
> Well I do have a project, I'll push it to remote and then let you guys know.

"Talk is cheap, show me the code." - Linus Torvalds
